import { createDynamoEntityStore } from "./dynamo-entity-store";
import { getTrucksTableName } from "./dynamodb";

export type TruckRecord = {
  truckBoardId: string;
  createdBy?: string;
  createdAt: string;
  updatedAt: string;
  postingStatus?: string;
  availableDate?: string;
  availableTime?: string;
  expirationDate?: string;
  expirationTime?: string;
  availableNow?: boolean;
  availableUntilDate?: string;
  hoursOfService?: string;
  remainingDriveHours?: string;
  earliestPickupTime?: string;
  latestPickupTime?: string;
  appointmentRequired?: boolean;
  capacityStatus?: string;
  currentCity?: string;
  currentState?: string;
  currentZip?: string;
  currentCountry?: string;
  currentAddress?: string;
  facilityName?: string;
  locationRadius?: string;
  equipmentType?: string;
  trailerType?: string;
  truckType?: string;
  truckNumber?: string;
  trailerNumber?: string;
  equipmentLength?: string;
  equipmentWidth?: string;
  equipmentHeight?: string;
  maxWeightCapacity?: string;
  doorType?: string;
  temperatureRange?: string;
  reeferUnitAvailable?: boolean;
  teamDriverAvailable?: boolean;
  powerOnlyAvailable?: boolean;
  dropTrailerAvailable?: boolean;
  liftgateAvailable?: boolean;
  palletJackAvailable?: boolean;
  strapsAvailable?: boolean;
  loadBarsAvailable?: boolean;
  tarpsAvailable?: boolean;
  chainsAvailable?: boolean;
  eTrackAvailable?: boolean;
  hazmatCertified?: boolean;
  tankerEndorsement?: boolean;
  twicCard?: boolean;
  teamService?: boolean;
  airRide?: boolean;
  foodGradeTrailer?: boolean;
  preferredDestinationCity?: string;
  preferredDestinationState?: string;
  preferredDestinationRegion?: string;
  preferredLanes?: string;
  avoidedLanes?: string;
  willingDeadheadMiles?: string;
  minimumTripMiles?: string;
  maximumTripMiles?: string;
  preferredStates?: string[];
  excludedStates?: string[];
  carrierName?: string;
  carrierMcNumber?: string;
  carrierDotNumber?: string;
  contactName?: string;
  contactPhone?: string;
  contactEmail?: string;
  driverName?: string;
  driverPhone?: string;
  dispatcherName?: string;
  dispatcherPhone?: string;
  dispatcherEmail?: string;
  desiredRate?: string;
  minimumRate?: string;
  rateType?: string;
  desiredRatePerMile?: string;
  minimumRatePerMile?: string;
  fuelSurchargePreference?: string;
  paymentTerms?: string;
  quickPayAccepted?: boolean;
  negotiableRate?: boolean;
  insuranceVerified?: boolean;
  authorityVerified?: boolean;
  safetyRating?: string;
  operatingAuthorityStatus?: string;
  cargoInsuranceAmount?: string;
  autoLiabilityAmount?: string;
  insuranceExpirationDate?: string;
  documents?: string[];
  publicNotes?: string;
  internalNotes?: string;
};

export type CreateTruckInput = Omit<TruckRecord, "createdAt" | "updatedAt">;

const store = createDynamoEntityStore<TruckRecord>({
  tableName: getTrucksTableName,
  idKey: "truckBoardId",
  label: "Trucks",
  kind: "trucks",
});

export const createTruck = store.create;
export const listAllTrucks = store.listAll;
export const listAllTrucksCached = store.listAllCached;
export const getTruckById = store.getById;
export const getTruckByIdCached = store.getByIdCached;
export const updateTruck = store.update;
export const deleteTruck = store.remove;
