/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TruckboardRouteImport } from './routes/truckboard'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as RfpsRouteImport } from './routes/rfps'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadsRouteImport } from './routes/loads'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as CarriersRouteImport } from './routes/carriers'
import { Route as BiddingRouteImport } from './routes/bidding'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TruckboardTruckBoardIdRouteImport } from './routes/truckboard.$truckBoardId'
import { Route as LoadsLoadIdRouteImport } from './routes/loads.$loadId'
import { Route as CarriersCarrierIdRouteImport } from './routes/carriers.$carrierId'
import { Route as InvoicesInvoiceIdPrintRouteImport } from './routes/invoices.$invoiceId.print'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'

const TruckboardRoute = TruckboardRouteImport.update({
  id: '/truckboard',
  path: '/truckboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const RfpsRoute = RfpsRouteImport.update({
  id: '/rfps',
  path: '/rfps',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadsRoute = LoadsRouteImport.update({
  id: '/loads',
  path: '/loads',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const CarriersRoute = CarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => rootRouteImport,
} as any)
const BiddingRoute = BiddingRouteImport.update({
  id: '/bidding',
  path: '/bidding',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TruckboardTruckBoardIdRoute = TruckboardTruckBoardIdRouteImport.update({
  id: '/$truckBoardId',
  path: '/$truckBoardId',
  getParentRoute: () => TruckboardRoute,
} as any)
const LoadsLoadIdRoute = LoadsLoadIdRouteImport.update({
  id: '/$loadId',
  path: '/$loadId',
  getParentRoute: () => LoadsRoute,
} as any)
const CarriersCarrierIdRoute = CarriersCarrierIdRouteImport.update({
  id: '/$carrierId',
  path: '/$carrierId',
  getParentRoute: () => CarriersRoute,
} as any)
const InvoicesInvoiceIdPrintRoute = InvoicesInvoiceIdPrintRouteImport.update({
  id: '/invoices/$invoiceId/print',
  path: '/invoices/$invoiceId/print',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/bidding': typeof BiddingRoute
  '/carriers': typeof CarriersRouteWithChildren
  '/communications': typeof CommunicationsRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/loads': typeof LoadsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRoute
  '/rfps': typeof RfpsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/truckboard': typeof TruckboardRouteWithChildren
  '/carriers/$carrierId': typeof CarriersCarrierIdRoute
  '/loads/$loadId': typeof LoadsLoadIdRoute
  '/truckboard/$truckBoardId': typeof TruckboardTruckBoardIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/invoices/$invoiceId/print': typeof InvoicesInvoiceIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/bidding': typeof BiddingRoute
  '/carriers': typeof CarriersRouteWithChildren
  '/communications': typeof CommunicationsRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/loads': typeof LoadsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRoute
  '/rfps': typeof RfpsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/truckboard': typeof TruckboardRouteWithChildren
  '/carriers/$carrierId': typeof CarriersCarrierIdRoute
  '/loads/$loadId': typeof LoadsLoadIdRoute
  '/truckboard/$truckBoardId': typeof TruckboardTruckBoardIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/invoices/$invoiceId/print': typeof InvoicesInvoiceIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/bidding': typeof BiddingRoute
  '/carriers': typeof CarriersRouteWithChildren
  '/communications': typeof CommunicationsRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/loads': typeof LoadsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRoute
  '/rfps': typeof RfpsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/truckboard': typeof TruckboardRouteWithChildren
  '/carriers/$carrierId': typeof CarriersCarrierIdRoute
  '/loads/$loadId': typeof LoadsLoadIdRoute
  '/truckboard/$truckBoardId': typeof TruckboardTruckBoardIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/invoices/$invoiceId/print': typeof InvoicesInvoiceIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/admin'
    | '/analytics'
    | '/bidding'
    | '/carriers'
    | '/communications'
    | '/crm'
    | '/dashboard'
    | '/landing'
    | '/loads'
    | '/login'
    | '/profile'
    | '/quotes'
    | '/rfps'
    | '/risk'
    | '/settings'
    | '/tracking'
    | '/truckboard'
    | '/carriers/$carrierId'
    | '/loads/$loadId'
    | '/truckboard/$truckBoardId'
    | '/admin/users/$userId'
    | '/invoices/$invoiceId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/admin'
    | '/analytics'
    | '/bidding'
    | '/carriers'
    | '/communications'
    | '/crm'
    | '/dashboard'
    | '/landing'
    | '/loads'
    | '/login'
    | '/profile'
    | '/quotes'
    | '/rfps'
    | '/risk'
    | '/settings'
    | '/tracking'
    | '/truckboard'
    | '/carriers/$carrierId'
    | '/loads/$loadId'
    | '/truckboard/$truckBoardId'
    | '/admin/users/$userId'
    | '/invoices/$invoiceId/print'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/admin'
    | '/analytics'
    | '/bidding'
    | '/carriers'
    | '/communications'
    | '/crm'
    | '/dashboard'
    | '/landing'
    | '/loads'
    | '/login'
    | '/profile'
    | '/quotes'
    | '/rfps'
    | '/risk'
    | '/settings'
    | '/tracking'
    | '/truckboard'
    | '/carriers/$carrierId'
    | '/loads/$loadId'
    | '/truckboard/$truckBoardId'
    | '/admin/users/$userId'
    | '/invoices/$invoiceId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  BiddingRoute: typeof BiddingRoute
  CarriersRoute: typeof CarriersRouteWithChildren
  CommunicationsRoute: typeof CommunicationsRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  LandingRoute: typeof LandingRoute
  LoadsRoute: typeof LoadsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  QuotesRoute: typeof QuotesRoute
  RfpsRoute: typeof RfpsRoute
  RiskRoute: typeof RiskRoute
  SettingsRoute: typeof SettingsRoute
  TrackingRoute: typeof TrackingRoute
  TruckboardRoute: typeof TruckboardRouteWithChildren
  InvoicesInvoiceIdPrintRoute: typeof InvoicesInvoiceIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/truckboard': {
      id: '/truckboard'
      path: '/truckboard'
      fullPath: '/truckboard'
      preLoaderRoute: typeof TruckboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfps': {
      id: '/rfps'
      path: '/rfps'
      fullPath: '/rfps'
      preLoaderRoute: typeof RfpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loads': {
      id: '/loads'
      path: '/loads'
      fullPath: '/loads'
      preLoaderRoute: typeof LoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carriers': {
      id: '/carriers'
      path: '/carriers'
      fullPath: '/carriers'
      preLoaderRoute: typeof CarriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bidding': {
      id: '/bidding'
      path: '/bidding'
      fullPath: '/bidding'
      preLoaderRoute: typeof BiddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truckboard/$truckBoardId': {
      id: '/truckboard/$truckBoardId'
      path: '/$truckBoardId'
      fullPath: '/truckboard/$truckBoardId'
      preLoaderRoute: typeof TruckboardTruckBoardIdRouteImport
      parentRoute: typeof TruckboardRoute
    }
    '/loads/$loadId': {
      id: '/loads/$loadId'
      path: '/$loadId'
      fullPath: '/loads/$loadId'
      preLoaderRoute: typeof LoadsLoadIdRouteImport
      parentRoute: typeof LoadsRoute
    }
    '/carriers/$carrierId': {
      id: '/carriers/$carrierId'
      path: '/$carrierId'
      fullPath: '/carriers/$carrierId'
      preLoaderRoute: typeof CarriersCarrierIdRouteImport
      parentRoute: typeof CarriersRoute
    }
    '/invoices/$invoiceId/print': {
      id: '/invoices/$invoiceId/print'
      path: '/invoices/$invoiceId/print'
      fullPath: '/invoices/$invoiceId/print'
      preLoaderRoute: typeof InvoicesInvoiceIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CarriersRouteChildren {
  CarriersCarrierIdRoute: typeof CarriersCarrierIdRoute
}

const CarriersRouteChildren: CarriersRouteChildren = {
  CarriersCarrierIdRoute: CarriersCarrierIdRoute,
}

const CarriersRouteWithChildren = CarriersRoute._addFileChildren(
  CarriersRouteChildren,
)

interface LoadsRouteChildren {
  LoadsLoadIdRoute: typeof LoadsLoadIdRoute
}

const LoadsRouteChildren: LoadsRouteChildren = {
  LoadsLoadIdRoute: LoadsLoadIdRoute,
}

const LoadsRouteWithChildren = LoadsRoute._addFileChildren(LoadsRouteChildren)

interface TruckboardRouteChildren {
  TruckboardTruckBoardIdRoute: typeof TruckboardTruckBoardIdRoute
}

const TruckboardRouteChildren: TruckboardRouteChildren = {
  TruckboardTruckBoardIdRoute: TruckboardTruckBoardIdRoute,
}

const TruckboardRouteWithChildren = TruckboardRoute._addFileChildren(
  TruckboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  BiddingRoute: BiddingRoute,
  CarriersRoute: CarriersRouteWithChildren,
  CommunicationsRoute: CommunicationsRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  LandingRoute: LandingRoute,
  LoadsRoute: LoadsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  QuotesRoute: QuotesRoute,
  RfpsRoute: RfpsRoute,
  RiskRoute: RiskRoute,
  SettingsRoute: SettingsRoute,
  TrackingRoute: TrackingRoute,
  TruckboardRoute: TruckboardRouteWithChildren,
  InvoicesInvoiceIdPrintRoute: InvoicesInvoiceIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
